# Generated by Django 4.1.2 on 2022-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='user',
            field=models.CharField(default=7647402737275, max_length=200, verbose_name='username'),
        ),
    ]
