# Generated by Django 4.1.2 on 2022-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzers', '0006_uploadchestimage_alter_uploadimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadchestimage',
            name='user',
            field=models.CharField(default=1672407383.6637237, max_length=200, verbose_name='username'),
        ),
    ]
