# Generated by Django 4.1.2 on 2022-12-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzers', '0007_uploadchestimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadKidneyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=1672492055.930115, max_length=200, verbose_name='username')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/chest_xray/')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadchestimage',
            name='user',
            field=models.CharField(default=1672492055.9271235, max_length=200, verbose_name='username'),
        ),
    ]
