# Generated by Django 4.1.2 on 2023-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzers', '0008_uploadkidneyimage_alter_uploadchestimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadchestimage',
            name='user',
            field=models.CharField(default=1672562860.413496, max_length=200, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/brain_tumor_scans/'),
        ),
        migrations.AlterField(
            model_name='uploadkidneyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/kidney_scans/'),
        ),
        migrations.AlterField(
            model_name='uploadkidneyimage',
            name='user',
            field=models.CharField(default=1672562860.4144928, max_length=200, verbose_name='username'),
        ),
    ]
