# Generated by Django 4.1.2 on 2023-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzers', '0010_alter_uploadchestimage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadchestimage',
            name='user',
            field=models.CharField(max_length=200, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='uploadkidneyimage',
            name='user',
            field=models.CharField(max_length=200, verbose_name='username'),
        ),
    ]
